#!/usr/bin/env python3
"""Write the local config for hustcer/deepseek-review from the workflow file.

The PR review on GitHub and the pre-flight review run here should be the same
reviewer: same model, temperature, exclusions and, above all, the same system
prompt. Two copies of that prompt would drift within a week. So there is one -
in .github/workflows/deepseek-review.yml, where the action reads it - and this
derives the CLI's config.yml from it each time the wrapper runs.

Secrets never touch the repository. The DeepSeek token comes from CHAT_TOKEN in
the environment, the GitHub token from `gh auth token`, and the file this
writes lands in the user's config directory with mode 600.

    review-config.py [--workflow FILE] [--out FILE]
"""

import argparse
import datetime as dt
import os
import subprocess
import sys
from pathlib import Path

import yaml

HERE = Path(__file__).resolve()
REPO = HERE.parents[2]
WORKFLOW = REPO / '.github' / 'workflows' / 'deepseek-review.yml'
OUT = Path(os.environ.get('XDG_CONFIG_HOME', Path.home() / '.config')) / 'deepseek-review' / 'config.yml'


def review_step(workflow: dict) -> dict:
    for job in workflow['jobs'].values():
        for step in job.get('steps', []):
            if 'deepseek-review' in str(step.get('uses', '')):
                return step['with']
    sys.exit(f'{WORKFLOW}: no step uses hustcer/deepseek-review')


def today() -> str:
    # the workflow's Today step: date -u '+%A %d %B %Y'
    return dt.datetime.now(dt.timezone.utc).strftime('%A %d %B %Y')


def gh_token() -> str:
    try:
        return subprocess.run(['gh', 'auth', 'token'], check=True, capture_output=True,
                              text=True).stdout.strip()
    except (OSError, subprocess.CalledProcessError):
        return ''


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument('--workflow', type=Path, default=WORKFLOW)
    ap.add_argument('--out', type=Path, default=OUT)
    args = ap.parse_args()

    with open(args.workflow, encoding='utf-8') as f:
        wf = yaml.safe_load(f)
    w = review_step(wf)
    sys_prompt = w['sys-prompt'].replace('${{ steps.today.outputs.date }}', today())
    if '${{' in sys_prompt:
        sys.exit('the system prompt has an expression this script does not know how to expand')

    chat_token = os.environ.get('CHAT_TOKEN', '')
    config = {
        'settings': {
            'provider': 'DeepSeek',
            'max-length': int(w.get('max-length', 0)),
            'temperature': float(w.get('temperature', 0.3)),
            'user-prompt': 'default',
            'system-prompt': 'default',
            'github-token': gh_token(),
            'default-github-repo': 'opengeofiction-net/danu',
            'include-patterns': w.get('include-patterns', ''),
            'exclude-patterns': w.get('exclude-patterns', ''),
        },
        'providers': [{
            'name': 'DeepSeek',
            'token': chat_token or 'SET CHAT_TOKEN IN YOUR ENVIRONMENT',
            'base-url': w.get('base-url', 'https://api.deepseek.com'),
            'models': [{'name': w.get('model', 'deepseek-v4-flash'), 'enabled': True}],
        }],
        'prompts': {
            'user': [{'name': 'default', 'prompt': w.get('user-prompt', 'Review the following changes.')}],
            'system': [{'name': 'default', 'prompt': sys_prompt}],
        },
    }

    args.out.parent.mkdir(parents=True, exist_ok=True)
    fd = os.open(args.out, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
    with os.fdopen(fd, 'w', encoding='utf-8') as f:
        f.write('# Generated by packaging/ci/review-config.py from the workflow - do not edit,\n'
                '# do not commit. Holds tokens.\n')
        yaml.safe_dump(config, f, sort_keys=False, allow_unicode=True, width=100)
    os.chmod(args.out, 0o600)
    if not chat_token:
        print('review-config: CHAT_TOKEN is not set; the config has a placeholder where the '
              'DeepSeek token goes', file=sys.stderr)
    return 0


if __name__ == '__main__':
    sys.exit(main())
